id: P001845
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 2021-12-17 10:25:28.760849
source_metadata:
  id: bdr:W1KG25009
  title: སུམ་རྟགས་སྙན་གསུམ་གྱི་རྩ་བ།
  author: ''
  volumes:
    15c51a5274a04b68b949290520939bff:
      image_group_id: I1KG25011
      title: ''
      volume_number: 1
      total_pages: 192
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
