id: P001845
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1KG25009
  title: སུམ་རྟགས་སྙན་གསུམ་གྱི་རྩ་བ།
  author: ''
  volumes:
    15c51a5274a04b68b949290520939bff:
      image_group_id: I1KG25011
      title: ''
      volume_number: 1
      total_pages: 192
      base_file: v001.txt
